#devices:
#  vRouter-1:
#    hostname: "192.168.1.1"
#    username: "R1"
#    password: "cisco"
#    ip_addresses:
##      - interface: GigabitEthernet0/1
##        address: "192.168.1.1"
##        mask: "255.255.255.0"
#      - interface: GigabitEthernet0/0
#        address: "10.10.20.1"
#        mask: "255.255.255.0"
#  vRouter-2:
#    hostname: "192.168.1.2"
#    username: "admin"
#    password: "admin"
#    ip_addresses:
##      - interface: GigabitEthernet0/0
##        address: "192.168.1.2"
##        mask: "255.255.255.0"
#      - interface: GigabitEthernet0/1
#        address: "10.10.20.2"
#        mask: "255.255.255.0"

######
devices:
  vRouter-1:
    hostname: "192.168.1.1"
    username: "R1"
    password: "cisco"
    ip_addresses:
      - interface: GigabitEthernet0/0
        address: "10.10.20.1"
        mask: "255.255.255.0"
    static_routes:
      - destination: "30.30.30.0"
        mask: "255.255.255.0"
        next_hop: "10.10.20.4"

  vRouter-2:
    hostname: "192.168.1.2"
    username: "R2"
    password: "cisco"
    ip_addresses:
      - interface: GigabitEthernet0/1
        address: "10.10.20.2"
        mask: "255.255.255.0"
    static_routes:
      - destination: "30.30.30.0"
        mask: "255.255.255.0"
        next_hop: "10.10.20.4"

  ISP1:
    hostname: "10.10.20.4"
    username: "ISP1"
    password: "cisco"
    ip_addresses:
      - interface: GigabitEthernet0/1
        address: "30.30.30.1"
        mask: "255.255.255.0"
    static_routes:
      - destination: "192.168.1.0"
        mask: "255.255.255.0"
        next_hop: "10.10.20.1"

  RouterLAN:
    hostname: "30.30.30.2"
    username: "RouterLAN"
    password: "cisco"

  R2:
    hostname: "50.50.50.2"
    username: "R2"
    password: "cisco"

  RouterServer:
    hostname: "60.60.60.2"
    username: "RouterServer"
    password: "cisco"

  ISP2:
    hostname: "40.40.40.1"
    username: "ISP2"
    password: "cisco"
####inca nu sunt configurate bine la partea de hsrp
  vRouter-8:
    hostname: "20.20.20.3"
    username: "R8"
    password: "cisco"
    hsrp:
      interface: "GigabitEthernet0/1"
      real_ip: "172.16.1.3"
      standby_ip: "172.16.1.254"
      priority: 110

  vRouter-9:
    hostname: "20.20.20.4"
    username: "R9"
    password: "cisco"
    hsrp:
      interface: "GigabitEthernet0/1"
      real_ip: "172.16.1.4"
      standby_ip: "172.16.1.254"
      priority: 100

#
#  SW_WAN1:
#      hostname: "10.10.20.3"
#      username: "admin"
#      password: "cisco"
#      hsrp:
#        interface: "GigabitEthernet0/2"
#        real_ip: "10.10.20.3"
#        standby_ip: "10.10.20.254"
#        priority: 110
#
#  ISP1:
#    hostname: "10.10.20.4"
#    username: "admin"
#    password: "cisco"
#    hsrp:
#      interface: "GigabitEthernet0/2"
#      real_ip: "10.10.20.4"
#      standby_ip: "10.10.20.254"
#      priority: 100

rip_devices:
  - ISP1
  - RouterLAN
  - R2
  - RouterServer
  - ISP2

hsrp_devices:
  - vRouter-8
  - vRouter-9